#!/bin/bash

# Prompts user for title of project
printf "Name of project:\t"
read projectName

# Prompts user for Learning Objectives
printf "\n\nPaste all learning objectives here then <ENTER> then <CTRL + D>:\n"
learningObjectives=$(cat)

# Prompts user for Requirements
printf "\n\nPaste all requirements here then <ENTER> then <CTRL + D>:\n"
requirements=$(cat)

# Write the base file template
{
echo "# $projectName

## Learning Objectives
#### At the end of this project, you are expected to be able to explain to anyone, without the help of Google:
"
# Adds a - at the beginning of each line
echo "$learningObjectives" | sed 's/^/- /'

echo "
## Requirements
"
# Adds a - at the beginning of each line
echo "$requirements" | sed 's/^/- /'
} > "README.md"
