#!/usr/bin/env bash
#This is a bash script that takes the data in the /etc/passwd and tells a "story".

IFS=":"
while read -r USERNAME PASSWORD USERID GROUPID USERIDI HOMEDIR COMMAND; do
	echo "The user $USERNAME is part of the $GROUPID gang, lives in $HOMEDIR and rides $COMMAND. $USERID's place is protected by the passcode $PASSWORD, more info about the user here: $USERIDI"
done < /etc/passwd
