#!/usr/bin/env bash
#This is a Bash script that prints Best School 10 times, but on the 9th time, it prints Hi.

x=0
while [ $x -lt 10 ]
do
	echo "Best School"
	((x++))
	if [ $x = 9 ]; then 
		echo "Hi"
	fi
done
