#!/usr/bin/env bash
#This is a while loop written in Bash that prints 1 through 20, but also indicates which numbers are bad luck in certain countries.

x=0

while [ $x -lt 20 ]
do
	#printf x && printf "\n"
	echo -e "$x"
	((x++))
	case $x in
	5)
		printf "bad luck from China"
		echo
		;;
	10)
		printf "bad luck from Japan"
		echo
		;;
	18)
		printf "bad luck from Italy"
		echo
		;;
	esac
done
