#!/usr/bin/env bash
#This is a Bash script that gives you information about the school file.

if [ -f school ]; then
	echo "school file exists"
	#echo "school is a regular file"
	#IF ABOVE IS TRUE AND....
	if [ -f school ] && [ -s school ]; then #checks if empty
		echo "school file is not empty"
		echo "school is a regular file"
	else
		echo "school file is empty"
		echo "school is a regular file"
	fi
elif [ -d school ]; then
	echo "school file exists"
	echo 
else
	echo "school file does not exist" 
fi
