#!/usr/bin/env bash
#bash script that does a lot of stuff

touch /var/run/myscript.pid
pgrep -f ./var/run/myscript.pid > /var/run/myscript.pid

trap "echo I hate the kill command; rm /var/run/myscript.pid; exit" SIGTERM
trap "echo Y U no love me?!; rm /var/run/myscript.pid; exit" SIGINT

x=11

while [ $x -gt 10 ]; do
        ((x++))
        echo "To infinity and beyond"
        sleep 2
done 
