#!/usr/bin/env bash
#displays "To infinity and beyond"

#x=11

#while [ $x -gt 10 ]; do
#        ((x++))
#        echo "To infinity and beyond"
#        sleep 2
#done

kill "$(pidof ./4-to_infinity_and_beyond)"

