#!/usr/bin/env bash
#displays "To infinity and beyond"

trap "echo I am invincible!!!" SIGTERM

x=11

while [ $x -gt 10 ]; do
        ((x++))
        echo "To infinity and beyond"
        sleep 2
done
